alias u="ultralist"
alias ua="ultralist a"
alias uac="ultralist archive c"
alias uc="ultralist c"
alias ud="ultralist d"
alias ud="ultralist d"
alias ue="ultralist e"
alias ul="ultralist l"
alias uo="ultralist l duebefore:tod"
alias up="ultralist p"
alias ut="ultralist l due:tod"

